/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Mon Jan 27 12:07:28 KST 2014
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

/*
Current MODEL ID is T_EF45K 
LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8960_EF45K
machine_is_msm8960_ef45k() function
*/

#define PT10  0x01
#define PT20  0x02
#define WS10  0x04
#define WS20  0x08
#define ES10  0x10
#define ES20  0x20
#define TP10  0x40
#define TP20  0x80
#define TP30  0x100

#define BOARD_VER   TP20
#endif /*BOARD_REV_H*/
